"""init

Revision ID: 1942180bfced
Revises: 1c3a60517971
Create Date: 2020-01-10 04:45:21.694007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1942180bfced'
down_revision = '1c3a60517971'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
